### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/Manati#16]
As shown in the screenshot below, once you mark something as legitimate or malicious, and you click on the filter to show 'undefined', the marked content doesn't go away. The same with any of the other filters.

<img width="1323" alt="screen shot 2018-08-29 at 11 09 53" src="https://user-images.githubusercontent.com/2458879/44777941-1ae04580-ab7c-11e8-9169-8d01e264a4c3.png">

**Comment by Piuliss** [comment]
fixed on version v0.11.1a
