### ISSUE TITLE
Saving user profile details redirects to non existent page

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/Manati#17]
After saving the user profile settings, ManaTI redirects to the following page: '/profile_form.html', which returns a Page Not Found error.

<img width="702" alt="screen shot 2018-08-29 at 11 24 43" src="https://user-images.githubusercontent.com/2458879/44778893-5a0f9600-ab7e-11e8-8083-0b69d6314d03.png">

**Comment by Piuliss** [comment]
fixed on version v0.11.1a
